### ISSUE TITLE
Wrong URL with latest version of laravel 5.5

### ISSUE THREAD

**Issue by DjWLaan** [WildSideUK/LaravelMailgunEu#4]
I did a composer update earlier today on my server and suddenly no mails were being sent. No errors, no logs... and no mail. Locally everything worked until I did the composer update. I'm not sure which package is at fault.

In any case, I did some digging into the MailgunTransporter and I saw that there is now an endpoint-parameter in the construct-function. This is used to build the url for the request.

Because of this, this package (WildSideUK/Laravel-MailgunEu), doesn't work any longer with the latest version of laravel 5.5 (at least 5.5.45, perhaps earlier).

Good news is, you can add an 'endpoint'-paramter in your services-config with the value eu.api.mailgun.net and everything will work out of the box.

PS: This is an already resolved issue (not really an issue at all) - but I didn't know where else to post it. I just wanted to spare my fellow humans the debug-hell I went through. Maybe put it in the readme?

**Comment by mattmcdev** [comment]
Thanks for pointing this out - have removed 5.5 support from this package.
